apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-4kes
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-4kes
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-4kes
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-4kes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-4kes
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lyng-tenant/rhtap-demo-app/hacbs-test-project-4kes@sha256:e443af441887f6d3d045fc0cefd22abe7602d77505ced102d5f928e7489af6c9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
